production:
  adapter:
  database:
  username:
  host:
  password:
  pool:
  timeout:

development:
  adapter:  sqlite3
  database: db/develop.db
  username:
  host:     localhost
  password:
  pool:
  timeout:

test:
  adapter:  sqlite3
  database: db/test.db
  username:
  host:     localhost
  password:
  pool:
  timeout:
