language: ruby
rvm:
  - 1.9.3

bundler_args: --without=development production

branches:
  only:
    - develop

script:
  - bundle exec rake db:migrate RACK_ENV=test
  - bundle exec rspec

after_success:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - heroku plugins:install https://github.com/ddollar/heroku-anvil
  - heroku build -r aqueous-tundra-2096  -b https://github.com/heroku/heroku-buildpack-ruby.git

env:
  global:
    - secure: ! 'slD/WxM228JboaySKzJ92dfwHL3MYaiD+W6ckfYhjTHY8ytct90cCr1+mkpW+7LBJa1JDeR3vRIEfu/QXqEc3mYC7xMibMMsQ74P1AztUMGDO0WXZskquJUfISlnqbJtdoMZWXE3Xong9/WuYwqPaShdFADyV2sNxmrCofszSAU='
