source :rubygems

gem 'sinatra'
gem 'rack'
gem 'activerecord'
gem 'sinatra-activerecord'

group :test do
	gem 'rack-test'
	gem 'rspec'
	gem 'database_cleaner'
end

group :development do
	gem 'sqlite3'
	gem 'shotgun'
end
