---
local: &local
  adapter:  sqlite3
  encoding: unicode
  username: ~
  password: ~
  host:     localhost
  pool:     ~
  timeout:  ~

remote: &remote
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  pool:     5
  timeout:  ~

production:
  <<: *remote
  database: ~
  username: ~
  password: ~

staging:
  <<: *remote
  database: ~
  username: ~
  password: ~

development:
  <<: *local
  database: db/develop.db

test:
  <<: *local
  database: db/test.db
